# Global seed to make evaluation reproducible
seed: 12
# Number of calibration passes to be applied to the model before export
calibration_passes: 8
# Model configuration section
model:
  # Number of attention heads
  num_heads: 6
  # Number of attention block "layers"
  num_layers: 1
  # Enables/disables bias on linear layers
  bias: true
  # Size of the input/output embedding dimension
  emb_dim: 144
  # Size of the MLP layer dimension
  mlp_dim: 576
  # Length of the input sequence, i.e., context size
  seq_len: 32
  # Number of bits to use for quantized representation
  bits: 4
  # Type of normalization layer to use in the transformer blocks
  #   Options are: layer-norm, batch-norm and none
  norm: none
  # Type of attention mask to use
  #   Options are: none, causal or const
  mask: none
  # Type of positional encoding to use at the input
  #   Options are: none, sinusoidal, binary, learned
  positional_encoding: binary
# Model to ONNX export hyperparameters
export:
  # Version of the default ONNX opset
  opset_version: 14
  # Apply the constant-folding optimization
  do_constant_folding: true
# FINN build configuration
build:
  # Directory to store the build outputs
  output_dir: build
  # Run synthesis to generate a .dcp for the stitched-IP output product
  stitched_ip_gen_dcp: false
  # Target clock period, i.e., inverse of target frequency
  synth_clk_period_ns: 10.0
  # Board to target with the build
  board: RFSoC2x2
  # Target shell flow: 'vivado_zynq' or 'vitis_alveo'
  shell_flow_type: vivado_zynq
  # Path to folding configuration file
  folding_config_file: folding.yaml
  # Path to layer implementation style specialization config
  specialize_layers_config_file: specialize_layers.json
  # Force the implementation of standalone thresholds to be able to use RTL
  # implementation of the MVU
  standalone_thresholds: true
  # Maximum bit-width of quantizers converted to multi-thresholds
  max_multithreshold_bit_width: 16
  # Maximum width of MVAU stream per PE
  mvau_wwidth_max: 128
#  # Optional: Start the build from a specific step
#  start_step: "step_tidy_up_pre_attention"
#  # Optional: Stop the build after a specific step
#  stop_step: "step_hw_ipgen"
# Metrics aggregation configuration
metrics:
  # Path to the report file to be summarized
  # Note: remember to adjust the build directory when changing the config above
  report: build/report/post_synth_resources.json
  # Filter the report rows
  filter: (top)
